// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: data_transfer.proto

package datatransfer

import (
	common "github.com/doanngocthanh9x/goocr/gen/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message cho file streaming
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Metadata      *common.Metadata       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_data_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_data_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_data_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *FileChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FileChunk) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Message response sau khi xử lý file
type ProcessFileResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *common.ProcessingStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Data          map[string]string        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessFileResponse) Reset() {
	*x = ProcessFileResponse{}
	mi := &file_data_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFileResponse) ProtoMessage() {}

func (x *ProcessFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFileResponse.ProtoReflect.Descriptor instead.
func (*ProcessFileResponse) Descriptor() ([]byte, []int) {
	return file_data_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessFileResponse) GetStatus() *common.ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ProcessFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ProcessFileResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// Message request JSON
type JsonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	Metadata      *common.Metadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonRequest) Reset() {
	*x = JsonRequest{}
	mi := &file_data_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRequest) ProtoMessage() {}

func (x *JsonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRequest.ProtoReflect.Descriptor instead.
func (*JsonRequest) Descriptor() ([]byte, []int) {
	return file_data_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *JsonRequest) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

func (x *JsonRequest) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Message response JSON
type JsonResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *common.ProcessingStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Data          map[string]string        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_data_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_data_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *JsonResponse) GetStatus() *common.ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *JsonResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *JsonResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_data_transfer_proto protoreflect.FileDescriptor

const file_data_transfer_proto_rawDesc = "" +
	"\n" +
	"\x13data_transfer.proto\x12\fdatatransfer\x1a\fcommon.proto\"\xad\x01\n" +
	"\tFileChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12,\n" +
	"\bmetadata\x18\x05 \x01(\v2\x10.common.MetadataR\bmetadata\"\xd9\x01\n" +
	"\x13ProcessFileResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.common.ProcessingStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12?\n" +
	"\x04data\x18\x03 \x03(\v2+.datatransfer.ProcessFileResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\vJsonRequest\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData\x12,\n" +
	"\bmetadata\x18\x02 \x01(\v2\x10.common.MetadataR\bmetadata\"\xcb\x01\n" +
	"\fJsonResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.common.ProcessingStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x128\n" +
	"\x04data\x18\x03 \x03(\v2$.datatransfer.JsonResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xac\x01\n" +
	"\x13DataTransferService\x12M\n" +
	"\vProcessFile\x12\x17.datatransfer.FileChunk\x1a!.datatransfer.ProcessFileResponse\"\x00(\x01\x12F\n" +
	"\vProcessJson\x12\x19.datatransfer.JsonRequest\x1a\x1a.datatransfer.JsonResponse\"\x00B3Z1github.com/doanngocthanh9x/goocr/gen/datatransferb\x06proto3"

var (
	file_data_transfer_proto_rawDescOnce sync.Once
	file_data_transfer_proto_rawDescData []byte
)

func file_data_transfer_proto_rawDescGZIP() []byte {
	file_data_transfer_proto_rawDescOnce.Do(func() {
		file_data_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_transfer_proto_rawDesc), len(file_data_transfer_proto_rawDesc)))
	})
	return file_data_transfer_proto_rawDescData
}

var file_data_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_data_transfer_proto_goTypes = []any{
	(*FileChunk)(nil),               // 0: datatransfer.FileChunk
	(*ProcessFileResponse)(nil),     // 1: datatransfer.ProcessFileResponse
	(*JsonRequest)(nil),             // 2: datatransfer.JsonRequest
	(*JsonResponse)(nil),            // 3: datatransfer.JsonResponse
	nil,                             // 4: datatransfer.ProcessFileResponse.DataEntry
	nil,                             // 5: datatransfer.JsonResponse.DataEntry
	(*common.Metadata)(nil),         // 6: common.Metadata
	(*common.ProcessingStatus)(nil), // 7: common.ProcessingStatus
}
var file_data_transfer_proto_depIdxs = []int32{
	6, // 0: datatransfer.FileChunk.metadata:type_name -> common.Metadata
	7, // 1: datatransfer.ProcessFileResponse.status:type_name -> common.ProcessingStatus
	4, // 2: datatransfer.ProcessFileResponse.data:type_name -> datatransfer.ProcessFileResponse.DataEntry
	6, // 3: datatransfer.JsonRequest.metadata:type_name -> common.Metadata
	7, // 4: datatransfer.JsonResponse.status:type_name -> common.ProcessingStatus
	5, // 5: datatransfer.JsonResponse.data:type_name -> datatransfer.JsonResponse.DataEntry
	0, // 6: datatransfer.DataTransferService.ProcessFile:input_type -> datatransfer.FileChunk
	2, // 7: datatransfer.DataTransferService.ProcessJson:input_type -> datatransfer.JsonRequest
	1, // 8: datatransfer.DataTransferService.ProcessFile:output_type -> datatransfer.ProcessFileResponse
	3, // 9: datatransfer.DataTransferService.ProcessJson:output_type -> datatransfer.JsonResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_data_transfer_proto_init() }
func file_data_transfer_proto_init() {
	if File_data_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_transfer_proto_rawDesc), len(file_data_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_transfer_proto_goTypes,
		DependencyIndexes: file_data_transfer_proto_depIdxs,
		MessageInfos:      file_data_transfer_proto_msgTypes,
	}.Build()
	File_data_transfer_proto = out.File
	file_data_transfer_proto_goTypes = nil
	file_data_transfer_proto_depIdxs = nil
}
