// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: data_transfer.proto

package datatransfer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataTransferService_ProcessFile_FullMethodName = "/datatransfer.DataTransferService/ProcessFile"
	DataTransferService_ProcessJson_FullMethodName = "/datatransfer.DataTransferService/ProcessJson"
)

// DataTransferServiceClient is the client API for DataTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service định nghĩa các RPC methods
type DataTransferServiceClient interface {
	// Nhận file và xử lý
	ProcessFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, ProcessFileResponse], error)
	// Nhận JSON và xử lý
	ProcessJson(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type dataTransferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataTransferServiceClient(cc grpc.ClientConnInterface) DataTransferServiceClient {
	return &dataTransferServiceClient{cc}
}

func (c *dataTransferServiceClient) ProcessFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, ProcessFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataTransferService_ServiceDesc.Streams[0], DataTransferService_ProcessFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, ProcessFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataTransferService_ProcessFileClient = grpc.ClientStreamingClient[FileChunk, ProcessFileResponse]

func (c *dataTransferServiceClient) ProcessJson(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DataTransferService_ProcessJson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataTransferServiceServer is the server API for DataTransferService service.
// All implementations must embed UnimplementedDataTransferServiceServer
// for forward compatibility.
//
// Service định nghĩa các RPC methods
type DataTransferServiceServer interface {
	// Nhận file và xử lý
	ProcessFile(grpc.ClientStreamingServer[FileChunk, ProcessFileResponse]) error
	// Nhận JSON và xử lý
	ProcessJson(context.Context, *JsonRequest) (*JsonResponse, error)
	mustEmbedUnimplementedDataTransferServiceServer()
}

// UnimplementedDataTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataTransferServiceServer struct{}

func (UnimplementedDataTransferServiceServer) ProcessFile(grpc.ClientStreamingServer[FileChunk, ProcessFileResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessFile not implemented")
}
func (UnimplementedDataTransferServiceServer) ProcessJson(context.Context, *JsonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessJson not implemented")
}
func (UnimplementedDataTransferServiceServer) mustEmbedUnimplementedDataTransferServiceServer() {}
func (UnimplementedDataTransferServiceServer) testEmbeddedByValue()                             {}

// UnsafeDataTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataTransferServiceServer will
// result in compilation errors.
type UnsafeDataTransferServiceServer interface {
	mustEmbedUnimplementedDataTransferServiceServer()
}

func RegisterDataTransferServiceServer(s grpc.ServiceRegistrar, srv DataTransferServiceServer) {
	// If the following call panics, it indicates UnimplementedDataTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataTransferService_ServiceDesc, srv)
}

func _DataTransferService_ProcessFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataTransferServiceServer).ProcessFile(&grpc.GenericServerStream[FileChunk, ProcessFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataTransferService_ProcessFileServer = grpc.ClientStreamingServer[FileChunk, ProcessFileResponse]

func _DataTransferService_ProcessJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransferServiceServer).ProcessJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataTransferService_ProcessJson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransferServiceServer).ProcessJson(ctx, req.(*JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataTransferService_ServiceDesc is the grpc.ServiceDesc for DataTransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataTransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datatransfer.DataTransferService",
	HandlerType: (*DataTransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessJson",
			Handler:    _DataTransferService_ProcessJson_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessFile",
			Handler:       _DataTransferService_ProcessFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "data_transfer.proto",
}
